name: "Continous Integration"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:         
          distribution: 'zulu'
          java-version: '25'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.16
      - name: Test with Surefire
        run: mvn test